In [19]:
import pandas as pd

In [20]:
df=pd.read_csv("heart.csv")

In [21]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [22]:
# convert text column into numeric value
from sklearn.preprocessing import OrdinalEncoder
le=OrdinalEncoder()

In [25]:
df[['ChestPainType','Sex','RestingECG','ExerciseAngina','ST_Slope']]=le.fit_transform(df[['ChestPainType','Sex','RestingECG','ExerciseAngina','ST_Slope']])

In [27]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1.0,1.0,140,289,0,1.0,172,0.0,0.0,2.0,0
1,49,0.0,2.0,160,180,0,1.0,156,0.0,1.0,1.0,1
2,37,1.0,1.0,130,283,0,2.0,98,0.0,0.0,2.0,0
3,48,0.0,0.0,138,214,0,1.0,108,1.0,1.5,1.0,1
4,54,1.0,2.0,150,195,0,1.0,122,0.0,0.0,2.0,0

In [38]:
from sklearn.model_selection import train_test_split

In [69]:
x=df.drop('HeartDisease',axis=1)
y=df.HeartDisease
x.shape

(918, 11)

In [70]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
x_scale=scale.fit_transform(x)

In [71]:
x_train,x_test,y_train,y_test=train_test_split(x_scale,y,test_size=0.2,random_state=30)

In [72]:
# create function that checkthe score of different model
def checkscore(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    print(model.score(x_test,y_test))

In [73]:
from sklearn.linear_model import LogisticRegression
checkscore(LogisticRegression(max_iter=1000),x_train,x_test,y_train,y_test)

0.8369565217391305

In [74]:
from sklearn.tree import DecisionTreeClassifier
checkscore(DecisionTreeClassifier(),x_train,x_test,y_train,y_test)

0.8152173913043478

In [75]:
from sklearn.svm import SVC
checkscore(SVC(),x_train,x_test,y_train,y_test)

0.875

In [76]:
# to remove less use dataset 
from sklearn.decomposition import PCA
pca=PCA(0.95)

In [77]:
x_pca=pca.fit_transform(x)

In [78]:
x_train_pca,x_test_pca,y_train_pca,y_test_pca=train_test_split(x_pca,y,test_size=0.2,random_state=30)

In [79]:
checkscore(LogisticRegression(),x_train_pca,x_test_pca,y_train_pca,y_test_pca)

0.7010869565217391